### ISSUE TITLE
proxy module not working rc.11

### ISSUE THREAD

**Issue by ironytr** [Teranode/nuxt-module-alternatives#97]
hello, proxy module ssr side isn't working (client side working) ssr side isn't adding necessary headers. (nuxt-proxy and vite proxy not working tho) maybe nuxt bug?
ssr side request
![image](https://user-images.githubusercontent.com/10614686/196387495-c78c0ae8-699b-4078-8767-bf97cb1f2ea7.png)
![image](https://user-images.githubusercontent.com/10614686/196388325-a8d7752d-e602-4a74-ada9-1f4c1af90e74.png)

client side request
![image](https://user-images.githubusercontent.com/10614686/196387590-a228cc19-0910-489a-8685-2abe84a8353d.png)
![image](https://user-images.githubusercontent.com/10614686/196388376-c7984674-6cf3-4029-bf03-a0ce79064dc6.png)

**Comment by Teranode** [comment]
1. I need to see your nuxt.config
2. Are you using the @nuxtjs-alt/http module
3. you had already dmed me this issue in discord, are you still using rc.12?

**Comment by ironytr** [comment]
hey,
freshly created a project. my backend is go lang.
https://github.com/ironytr/ssrproxynotworking

**Comment by Teranode** [comment]
you cannot use `$fetch` or `useFetch` with the proxy module. `ohmyfetch` runs before the proxy module is registered in nitro, you have to use `@nuxtjs-alt/http`

**Comment by ironytr** [comment]
thank you for answer,
i had errors with that http module. (tried newly created project tho)

```
npx nuxi init new-app
yarn add @nuxtjs-alt/http@latest
yarn
yarn dev
```

``` ERROR  [worker reload] [worker init] Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'```` 
![image](https://user-images.githubusercontent.com/10614686/196398482-1a0e1e7a-0b3f-4692-ac59-8b8559709f99.png)

**Comment by Teranode** [comment]
can you also try with the build/preview commands, I do not have my setup in a windows environment.

**Comment by Teranode** [comment]
Also try the latest version I just pushed

**Comment by ironytr** [comment]
hey, build, preview working, dev is not working the error continues
 "@nuxtjs-alt/http": "^1.3.16",

![image](https://user-images.githubusercontent.com/10614686/196413180-4bd15d0d-57a7-4cf8-a1fb-75a680107b12.png)

**Comment by Teranode** [comment]
try `1.3.17` in dev mode

**Comment by ironytr** [comment]
still continues 
``    "@nuxtjs-alt/http": "latest",
``
![image](https://user-images.githubusercontent.com/10614686/196437374-aacfe4e2-bdd2-4ddc-bf00-9b8df2de3cb2.png)

**Comment by Teranode** [comment]
yea, then im not sure how I would make that work in a windows enviroment.

**Comment by Teranode** [comment]
@ironytr try 1.3.18

**Comment by twuncher** [comment]
I was getting the same problem on windows 10, 

`nuxt.options.nitro.plugins.push(resolver.resolve((nuxt.options.dev && process.platform === "win32" ? pathToFileURL(nuxt.options.buildDir).href : nuxt.options.buildDir), `nitro-http${nuxt.options.dev ? ".mjs" : ".ts"}`);)`

in module.ts is the culprite - i commented it out and it now works - it seems like a transpile issue.

**Comment by ironytr** [comment]
> I was getting the same problem on windows 10,
> 
> `nuxt.options.nitro.plugins.push(resolver.resolve((nuxt.options.dev && process.platform === "win32" ? pathToFileURL(nuxt.options.buildDir).href : nuxt.options.buildDir), `nitro-http${nuxt.options.dev ? ".mjs" : ".ts"}`);)`
> 
> in module.ts is the culprite - i commented it out and it now works - it seems like a transpile issue.

hey, as you mentioned commenting out that line makes work `node_modules\@nuxtjs-alt\http\dist\module.mjs` . result of the module client side ssr not working, server side is working.

**Comment by twuncher** [comment]
I'm not at my machine right now, but I did play around with it, I got rid of the first error by using a relative path instead of an absolute path for the nitro plugin.

I got stuck on the next error where it started complaining about #imports, maybe someone can take it further, il give it another go tomorrow.

**Comment by twuncher** [comment]
I stepped through the nitro code and it does not handle file paths as absolute in its resolve function, so it trys to append it to app root server folder, creating an unreachable file and if you use the none file format it will complain that it needs to be in the  file format.

I will see if I can raise a bug issue with the nuxt team. In the meantime you can just extract the code and put it into a file in the server/plugins folder using the example of definenuxtplugin from the documentation. The latest commit basically does not import the nitro plugin anymore if you are running Windows.

**Comment by ironytr** [comment]
> I stepped through the nitro code and it does not handle file paths as absolute in its resolve function, so it trys to append it to app root server folder, creating an unreachable file and if you use the none file format it will complain that it needs to be in the file format.
> 
> I will see if I can raise a bug issue with the nuxt team. In the meantime you can just extract the code and put it into a file in the server/plugins folder using the example of definenuxtplugin from the documentation. The latest commit basically does not import the nitro plugin anymore if you are running Windows.

thank you for kindness and work.
